package com.ldx.conversationbase.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ldx.conversationbase.db.XIChatMessageBean;

import com.ldx.conversationbase.db.XIChatMessageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig xIChatMessageBeanDaoConfig;

    private final XIChatMessageBeanDao xIChatMessageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        xIChatMessageBeanDaoConfig = daoConfigMap.get(XIChatMessageBeanDao.class).clone();
        xIChatMessageBeanDaoConfig.initIdentityScope(type);

        xIChatMessageBeanDao = new XIChatMessageBeanDao(xIChatMessageBeanDaoConfig, this);

        registerDao(XIChatMessageBean.class, xIChatMessageBeanDao);
    }
    
    public void clear() {
        xIChatMessageBeanDaoConfig.clearIdentityScope();
    }

    public XIChatMessageBeanDao getXIChatMessageBeanDao() {
        return xIChatMessageBeanDao;
    }

}
